repos:
  #
  # Run unit tests
  #
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest test/
        language: system
        types: [python]
        args: ["--cov=src"]
        pass_filenames: false
        always_run: True

  #
  # Run the ruff linter + code-fixes
  #
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.14.5
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  #
  # Run the pyright type checker
  #
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.407          # use latest release
    hooks:
      - id: pyright
